//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_SalesOrderAddOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAccount
    {
        public int ID { get; set; }
        public string AccountID { get; set; }
        public string PaymentTermsID { get; set; }
        public string AccountName { get; set; }
        public string AccountAddress { get; set; }
        public string Status { get; set; }
        public string CustomerGroupCode { get; set; }
    }
}
