//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_SalesOrderAddOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPriceList
    {
        public int ID { get; set; }
        public string ProductID { get; set; }
        public string UoM { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<System.DateTime> EffectivityDate { get; set; }
        public string Status { get; set; }
    }
}
