//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_SalesOrderAddOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSupplier
    {
        public int ID { get; set; }
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierNameNoComma { get; set; }
        public string TaxType { get; set; }
        public string Incoterms { get; set; }
        public string IncotermsLocation { get; set; }
        public string Currency { get; set; }
    }
}
