//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISalesAddonDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAPMatrixDistributionFee
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string SupplierID { get; set; }
        public string CustomerGroupDescription { get; set; }
        public string CustomerGroupCode { get; set; }
        public Nullable<int> OtherCriteriaID { get; set; }
        public string DistributionMarginRate { get; set; }
    }
}
