//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISalesAddonDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCreditMemoFeeBasi
    {
        public int ID { get; set; }
        public string CreditMemoFeeBasisID { get; set; }
        public string CreditMemoFeeBasisDescription { get; set; }
    }
}
