//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISalesAddonDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPostingErrorLog
    {
        public int ID { get; set; }
        public string salesOrderID { get; set; }
        public string errorDescription { get; set; }
        public Nullable<System.DateTime> errorDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<int> errorTypeID { get; set; }
    }
}
