//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISalesAddonDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        public int ID { get; set; }
        public string ProductID { get; set; }
        public string SupplierID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string CategoryName { get; set; }
        public string PackSize { get; set; }
        public string UoM { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public string ProductCategoryID { get; set; }
    }
}
