//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISalesAddonDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSalesOrderLine
    {
        public int ID { get; set; }
        public string SalesOrderID { get; set; }
        public Nullable<int> SalesOrderLineID { get; set; }
        public string SAP_SalesOrderID { get; set; }
        public string SAP_SalesOrderLineID { get; set; }
        public string ProductID { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string FreeGood { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UoM { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> GrossAmount { get; set; }
        public Nullable<double> Discount1Amount { get; set; }
        public Nullable<double> Discount2Amount { get; set; }
        public Nullable<double> SalesOrderLineAmount { get; set; }
        public string TransactionStatus { get; set; }
        public string ExternalLineReference { get; set; }
    }
}
