//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISalesAddonDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSalesInvoiceLine
    {
        public int ID { get; set; }
        public string SalesInvoiceID { get; set; }
        public string SalesInvoiceLineID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceAmount { get; set; }
        public string AmountPaid { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string ProductID { get; set; }
        public string UnitPrice { get; set; }
    }
}
