//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISalesAddonDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tShippingAddress
    {
        public int ID { get; set; }
        public string ShippingAddressID { get; set; }
        public string AccountID { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingAddressNoComma { get; set; }
        public string Status { get; set; }
        public string DefaultShipTo { get; set; }
    }
}
