//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISalesAddonDEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalesOrderHeaderList
    {
        public string AccountName { get; set; }
        public string SalesOrderID { get; set; }
        public string SAP_SalesOrderID { get; set; }
        public string EmployeeID { get; set; }
        public string AccountID { get; set; }
        public string AccountContactID { get; set; }
        public string PaymentTermsID { get; set; }
        public string SupplierID { get; set; }
        public Nullable<System.DateTime> SalesOrderCreationDate { get; set; }
        public string Description { get; set; }
        public string ExternalReference { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<double> SalesOrderAmount { get; set; }
        public string Comments { get; set; }
        public string SAP_Status { get; set; }
        public string SupplierName { get; set; }
        public int ID { get; set; }
        public Nullable<int> TransactionStatusID { get; set; }
        public string statusDescription { get; set; }
    }
}
